name: Tag & Release

on:
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      - name: Install dependencies
        run: make install
      - name: Run Tests
        run: make test
  release:
    runs-on: ubuntu-latest
    needs: test
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: "release"
      - name: Build tag
        run: |
          echo "SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{secrets.PACKAGE_VERSION}}-${{env.SHA_SHORT}}',
              sha: context.sha
            })
      - name: Release
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createRelease({
              draft: false,
              generate_release_notes: true,
              name: 'Release ${{secrets.PACKAGE_VERSION}}-${{env.SHA_SHORT}}',
              owner: context.repo.owner,
              prerelease: false,
              repo: context.repo.repo,
              tag_name: '${{secrets.PACKAGE_VERSION}}-${{env.SHA_SHORT}}',
            })